//! Stoatworks Labs — About window data for UnMapper.
//!
//! GENERATED by stoatworks-backend/scripts/sync-about.py on 2026-08-03. Do not
//! edit: the next sync overwrites it. The facts come from the website's
//! projects.json, which is the one place they are written down.
//!
//! `version` here is a fallback read from this repo's own manifest at sync
//! time. Anything with a build step injects the real one at build time and
//! overrides this.

// Not every consumer shows every field - a CLI has no use for the
// mark and an egui window has none for the slug - and an unused
// constant here is the generator being complete, not a mistake.
#![allow(dead_code)]

pub const NAME: &str = "UnMapper";
pub const SLUG: &str = "unmapper";
pub const HOOK: &str = "Rehearse an LED rig without the LED";
pub const LICENCE: &str = "MIT";
pub const GUIDE: &str = "https://stoatworks-labs.com/software/unmapper/guide/";
pub const PAGE: &str = "https://stoatworks-labs.com/software/unmapper/";
pub const REPO: &str = "https://github.com/stoatworks-labs/UnMapper";
pub const VERSION_FALLBACK: &str = "v0.1.0";

pub const ORG: &str = "Stoatworks Labs";
pub const HOME: &str = "https://stoatworks-labs.com";
pub const TAGLINE: &str = "Open tools for the people who run the show.";

/// The canonical funding links, matching FUNDING.yml and the support footer.
pub const FUNDING: [(&str, &str); 4] = [
    ("GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs"),
    ("Ko-fi", "https://ko-fi.com/stoatworkslabs"),
    ("Patreon", "https://patreon.com/StoatworksLabs"),
    ("Liberapay", "https://liberapay.com/stoatworks-labs"),
];
